name: residence
description: Village Tech Residence App - Mobile app for residents
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3

  # Supabase
  supabase_flutter: ^2.0.0

  # Routing
  go_router: ^13.0.0

  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Environment Variables
  flutter_dotenv: ^5.1.0

  # UI
  cupertino_icons: ^1.0.6

  # Utilities
  intl: ^0.19.0
  image_picker: ^1.0.7
  file_picker: ^6.1.1
  qr_flutter: ^4.1.0
  mobile_scanner: ^3.5.5

  # Push Notifications
  flutter_local_notifications: ^16.3.0

  # Payments
  flutter_stripe: ^10.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.7
  riverpod_generator: ^2.3.9
  hive_generator: ^2.0.1
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - .env
