name: sentinel
description: Village Tech Sentinel App - Mobile app for security officers
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  equatable: ^2.0.5

  # Supabase
  supabase_flutter: ^2.0.0

  # Routing
  go_router: ^13.0.0

  # Local Storage (Offline Support)
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  drift: ^2.14.0
  drift_flutter: ^0.1.0
  sqlite3_flutter_libs: ^0.5.18

  # Environment Variables
  flutter_dotenv: ^5.1.0

  # UI
  cupertino_icons: ^1.0.6

  # Utilities
  intl: ^0.19.0
  image_picker: ^1.0.7
  file_picker: ^6.1.1
  qr_flutter: ^4.1.0
  mobile_scanner: ^3.5.5

  # Push Notifications
  flutter_local_notifications: ^16.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.7
  hive_generator: ^2.0.1
  drift_dev: ^2.14.0
  bloc_test: ^9.1.5
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - .env
