/**
 * This file will be auto-generated by Supabase CLI
 * Run: npm run supabase:types
 *
 * Placeholder until database migrations are created
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      // Tables will be generated here after migrations
    }
    Views: {
      // Views will be generated here after migrations
    }
    Functions: {
      // Functions will be generated here after migrations
    }
    Enums: {
      // Enums will be generated here after migrations
    }
  }
}
