name: Sentinel App Build

on:
  push:
    branches: [main, master]
    paths:
      - 'apps/sentinel/**'
      - '.github/workflows/sentinel-build.yml'
  pull_request:
    branches: [main, master]
    paths:
      - 'apps/sentinel/**'

jobs:
  analyze-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/sentinel

    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.0'
          channel: 'stable'

      - name: Get dependencies
        run: flutter pub get

      - name: Run analyzer
        run: flutter analyze

      - name: Run tests
        run: flutter test

  build-android:
    needs: analyze-and-test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/sentinel

    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.0'
          channel: 'stable'

      - name: Get dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: sentinel-apk
          path: apps/sentinel/build/app/outputs/flutter-apk/app-release.apk
